### PR TITLE
feat: add another Symfony runtime

### PR DESCRIPTION
**Pull request by FluffyDiscord**
## Summary by CodeRabbit

- **Documentation**
	- Updated the Symfony integration guide to include the new `FluffyDiscord/roadrunner-symfony-bundle` repository along with its version and license status badges.

### CODE REVIEW

**Comment by rustatian** [comment]
@FluffyDiscord Is that a fork of the `Baldinof` runtime?

**Comment by FluffyDiscord** [comment]
No, its built from the ground up

**Comment by rustatian** [comment]
Done, thanks @FluffyDiscord 👍

**Comment by FluffyDiscord** [comment]
By the way this is still using old docs:
image

**Comment by rustatian** [comment]
Fixed 👍 Thanks

**Pull request merged**
